name: nutrra
description: Nutrra test

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  dio_flutter_transformer: ^3.0.2
  provider: ^4.1.3
  email_validator: ^1.0.4
  get_it: ^4.0.2
  jwt_decoder: ^1.0.1
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^3.3.0
  json_annotation: ^3.0.1
  build_runner: ^1.10.0
  intl_translation: ^0.17.9


flutter:
  uses-material-design: true
